/* XiHunJi Supabase bridge: Digital Invitation -> RSVP -> Guest Management */
(()=>{'use strict';
const CFG={url:'https://ztpxjwqjnrosdagsasjk.supabase.co',key:'sb_publishable_8AJOnIeY04M0J8l72D9xIg_3n4yyo5k'};
let sb=null,user=null,busy=false,preview=false,channel=null;
const cloudState=()=>{state.cloud=Object.assign({invitationId:''},state.cloud||{});return state.cloud};
const signed=()=>!!(sb&&user);
const guestRoute=()=>{const u=new URL(location.href);return u.searchParams.get('view')==='guest'&&!!u.searchParams.get('invite')};
const token=()=>new URL(location.href).searchParams.get('invite')||state.invite?.token||'';
const iso=v=>{if(!v)return null;const d=new Date(v);return isNaN(d)?null:d.toISOString()};
const localDT=v=>{if(!v)return'';const d=new Date(v);if(isNaN(d))return'';const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`};
async function init(){if(sb)return sb;if(!window.supabase?.createClient)return null;sb=window.supabase.createClient(CFG.url,CFG.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await sb.auth.getSession();user=data.session?.user||null;sb.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;if(currentView==='settings')renderSettings();if(user)watchGuests()});return sb}
function invitePayload(){return{public_token:state.invite.token,groom:state.profile.groom||'',bride:state.profile.bride||'',date_time:iso(state.invite.dateTime||(state.profile.date?state.profile.date+'T18:00':'')),venue_name:state.profile.venue||'',venue_address:state.invite.venueAddress||'',cover_photo_url:state.invite.coverPhoto||'',story:state.invite.story||'',message:state.invite.message||'',language:state.invite.lang||'中英双语',theme_music_url:state.invite.themeMusic||''}}
function applyInvite(r,t=''){if(!r)return;ensureInviteDefaults();cloudState();state.cloud.invitationId=r.id||state.cloud.invitationId;state.invite.token=t||r.public_token||state.invite.token;state.profile.groom=r.groom||'';state.profile.bride=r.bride||'';state.profile.venue=r.venue_name||'';state.invite.dateTime=localDT(r.date_time);if(state.invite.dateTime)state.profile.date=state.invite.dateTime.slice(0,10);state.invite.venueAddress=r.venue_address||'';state.invite.coverPhoto=r.cover_photo_url||state.invite.coverPhoto;state.invite.story=r.story||'';state.invite.message=r.message||'';state.invite.lang=r.language||'中英双语';state.invite.themeMusic=r.theme_music_url||'';saveState(true)}
const mapTable=r=>({id:r.id,cloudId:r.id,name:r.name,capacity:Number(r.capacity||10)});
const mapGuest=r=>normalizeGuest({id:r.id,cloudId:r.id,name:r.guest_name,side:r.side,rsvp:r.attendance,pax:Number(r.attendee_count||0),diet:r.dietary_requirements||[],message:r.message||'',source:r.source||'manual',table:r.table_id||'',seats:r.seat_numbers||[],createdAt:r.created_at,updatedAt:r.updated_at});
async function ensureInvite(){cloudState();if(!signed())throw Error('请先登录新人账号');if(state.cloud.invitationId){const q=await sb.from('invitations').select('*').eq('id',state.cloud.invitationId).maybeSingle();if(q.data)return q.data;state.cloud.invitationId=''}const q=await sb.from('invitations').select('*').order('updated_at',{ascending:false}).limit(1);if(q.error)throw q.error;if(q.data?.length){state.cloud.invitationId=q.data[0].id;saveState(true);return q.data[0]}const ins=await sb.from('invitations').insert({owner_id:user.id,...invitePayload()}).select('*').single();if(ins.error)throw ins.error;state.cloud.invitationId=ins.data.id;state.invite.token=ins.data.public_token||state.invite.token;saveState(true);return ins.data}
async function pushInvite(show=false){if(!signed()){if(show)toast('请先到设置与云端登录');return false}try{const r=await ensureInvite();const q=await sb.from('invitations').update(invitePayload()).eq('id',r.id).select('*').single();if(q.error)throw q.error;state.cloud.invitationId=q.data.id;saveState(true);if(show)toast('电子请柬已同步云端');return true}catch(e){console.error(e);if(show)toast('云端同步失败：'+e.message);return false}}
async function pushTable(t){const inv=await ensureInvite();if(t.cloudId){const q=await sb.from('wedding_tables').update({name:t.name,capacity:Number(t.capacity||10)}).eq('id',t.cloudId).select('*').single();if(q.error)throw q.error;t.id=q.data.id;t.cloudId=q.data.id;return}const old=t.id,q=await sb.from('wedding_tables').insert({invitation_id:inv.id,name:t.name,capacity:Number(t.capacity||10)}).select('*').single();if(q.error)throw q.error;t.id=q.data.id;t.cloudId=q.data.id;state.guests.forEach(g=>{if(g.table===old)g.table=t.id})}
async function pushGuest(g){if(!g)return;const inv=await ensureInvite();let tableId=null;if(g.table){const t=state.tables.find(x=>x.id===g.table||x.cloudId===g.table);if(t){if(!t.cloudId)await pushTable(t);tableId=t.cloudId||t.id}}const p={invitation_id:inv.id,guest_name:g.name,side:g.side||'other',attendance:g.rsvp||'pending',attendee_count:g.rsvp==='going'?guestPax(g):0,dietary_requirements:normalizeDiets(g.diet),message:g.message||'',source:g.source||'manual',table_id:tableId,seat_numbers:Array.isArray(g.seats)?g.seats:[]};const q=g.cloudId?await sb.from('guests').update(p).eq('id',g.cloudId).select('*').single():await sb.from('guests').insert(p).select('*').single();if(q.error)throw q.error;g.id=q.data.id;g.cloudId=q.data.id}
async function uploadAll(){if(busy)return;if(!signed())return toast('请先登录新人账号');busy=true;try{await pushInvite(false);for(const t of state.tables)await pushTable(t);for(const g of state.guests)await pushGuest(g);reallocateAllSeats();for(const g of state.guests)if(g.cloudId)await pushGuest(g);saveState(true);watchGuests();renderCurrent();toast('目前资料已上传到 Supabase')}catch(e){console.error(e);toast('上传失败：'+e.message)}finally{busy=false}}
async function pullAll(show=true){if(busy)return;if(!signed()){if(show)toast('请先登录新人账号');return}busy=true;try{cloudState();let inv=null;if(state.cloud.invitationId){const q=await sb.from('invitations').select('*').eq('id',state.cloud.invitationId).maybeSingle();inv=q.data||null}if(!inv){const q=await sb.from('invitations').select('*').order('updated_at',{ascending:false}).limit(1);if(q.error)throw q.error;inv=q.data?.[0]||null}if(!inv){if(show)toast('云端还没有婚礼资料，请先上传');return}applyInvite(inv);const [t,g]=await Promise.all([sb.from('wedding_tables').select('*').eq('invitation_id',inv.id).order('created_at'),sb.from('guests').select('*').eq('invitation_id',inv.id).order('created_at',{ascending:false})]);if(t.error)throw t.error;if(g.error)throw g.error;state.tables=(t.data||[]).map(mapTable);state.guests=(g.data||[]).map(mapGuest);reallocateAllSeats();saveState(true);watchGuests();renderCurrent();if(show)toast('已同步最新 RSVP')}catch(e){console.error(e);if(show)toast('读取云端失败：'+e.message)}finally{busy=false}}
async function refreshGuests(){if(!signed()||!state.cloud?.invitationId)return;const q=await sb.from('guests').select('*').eq('invitation_id',state.cloud.invitationId).order('created_at',{ascending:false});if(q.error)return console.error(q.error);state.guests=(q.data||[]).map(mapGuest);reallocateAllSeats();saveState(true);if(['guests','invite','overview'].includes(currentView))renderCurrent()}
function watchGuests(){if(!signed()||!state.cloud?.invitationId)return;try{if(channel)sb.removeChannel(channel);channel=sb.channel('xhj-'+state.cloud.invitationId).on('postgres_changes',{event:'*',schema:'public',table:'guests',filter:`invitation_id=eq.${state.cloud.invitationId}`},async()=>{await refreshGuests();toast('收到新的 RSVP')}).subscribe()}catch(e){console.error(e)}}
async function auth(mode){await init();const email=document.getElementById('cloudEmail')?.value.trim(),password=document.getElementById('cloudPassword')?.value||'';if(!email||password.length<6)return toast('请输入 Email 与至少 6 位密码');try{const r=mode==='signup'?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;user=r.data.user||r.data.session?.user||null;renderSettings();toast(mode==='signup'&&!r.data.session?'账号已建立，请到邮箱确认':'登录成功')}catch(e){toast('登录失败：'+e.message)}}
async function logout(){if(!sb)return;await sb.auth.signOut();user=null;renderSettings();toast('已退出 Supabase')}
function invalid(msg='邀请链接无效或已更新'){const root=ensureInvitationPortal();root.innerHTML=`<div style="min-height:100vh;display:grid;place-items:center;padding:30px;background:#f8f2e9"><div class="guest-card" style="max-width:430px;text-align:center"><div class="invite-confirm-icon">囍</div><h2 class="serif">${esc(msg)}</h2><p class="muted" style="font-size:12px;line-height:1.8">请向新人索取最新电子请柬链接。</p></div></div>`;root.classList.remove('hidden')}
const oldOpen=openGuestInvitation;openGuestInvitation=function(p=false){preview=!!p;return oldOpen(p)};
const oldDebounce=debounceInviteSave;debounceInviteSave=function(){oldDebounce();if(signed()){clearTimeout(window.__cloudsave);window.__cloudsave=setTimeout(()=>pushInvite(false),900)}};
const oldAssign=assignTable;assignTable=async function(gid,tid){oldAssign(gid,tid);const g=state.guests.find(x=>x.id===gid||x.cloudId===gid);if(g&&signed())try{await pushGuest(g);saveState(true)}catch(e){console.error(e);toast('桌席已本地保存；云端同步失败')}};
const oldAddGuest=addGuest;addGuest=async function(){const ids=new Set(state.guests.map(g=>g.id));oldAddGuest();const g=state.guests.find(x=>!ids.has(x.id));if(g&&signed())try{await pushGuest(g);saveState(true);renderGuests()}catch(e){console.error(e)}};
const oldAddTable=addTable;addTable=async function(){const ids=new Set(state.tables.map(t=>t.id));oldAddTable();const t=state.tables.find(x=>!ids.has(x.id));if(t&&signed())try{await pushTable(t);saveState(true);renderGuests()}catch(e){console.error(e)}};
const oldDelete=deleteGuest;deleteGuest=async function(id){const g=state.guests.find(x=>x.id===id);if(g?.cloudId&&signed()){const q=await sb.from('guests').delete().eq('id',g.cloudId);if(q.error)return toast('云端删除失败')}oldDelete(id)};
const oldAuto=autoSeat;autoSeat=async function(){oldAuto();if(signed())try{for(const t of state.tables)if(!t.cloudId)await pushTable(t);for(const g of state.guests)await pushGuest(g);saveState(true);renderGuests()}catch(e){console.error(e)}};
const oldRenderGuests=renderGuests;renderGuests=function(){oldRenderGuests();const h=document.querySelector('#view-guests .page-head');if(h&&!h.querySelector('.xhj-sync')){const b=document.createElement('button');b.className='btn btn-secondary btn-small xhj-sync';b.textContent='↻ 同步 RSVP';b.onclick=()=>pullAll();h.appendChild(b)}};
submitGuestRSVP=async function(ev){ev.preventDefault();ensureInviteDefaults();const f=ev.currentTarget,e=document.getElementById('rsvpError'),name=f.guest_name.value.trim(),side=f.side.value,attendance=f.attendance.value;if(!name||!side||!attendance){e.textContent='请填写姓名、亲友关系和出席状态。';e.style.display='block';return}const pax=attendance==='going'?Math.max(1,Math.min(10,Number(f.attendee_count.value||1))):0,diets=[...f.querySelectorAll('input[name="diet"]:checked')].map(x=>x.value),message=f.message.value.trim(),btn=f.querySelector('button[type="submit"]');if(btn){btn.disabled=true;btn.textContent=preview?'预览中…':'正在提交…'}try{if(preview)await new Promise(r=>setTimeout(r,200));else if(guestRoute()){await init();const q=await sb.rpc('submit_public_rsvp',{p_token:token(),p_guest_name:name,p_side:side,p_attendance:attendance,p_attendee_count:pax,p_dietary_requirements:diets,p_message:message});if(q.error)throw q.error}else{let g=state.guests.find(x=>x.source==='digital_invitation'&&x.name.toLowerCase()===name.toLowerCase()&&x.side===side);if(g)Object.assign(g,{rsvp:attendance,pax,diet:diets,message,table:attendance==='going'?g.table:'',seats:attendance==='going'?g.seats:[]});else{g=normalizeGuest({id:uid('g'),name,side,rsvp:attendance,pax,diet:diets,message,source:'digital_invitation',table:'',seats:[]});state.guests.unshift(g)}reallocateAllSeats();saveState(true);if(signed())await pushGuest(g)}e.style.display='none';document.getElementById('confirmTitle').textContent=preview?'预览提交成功':attendance==='going'?'期待婚礼当天见到你':'谢谢你告诉我们';document.getElementById('confirmText').textContent=preview?'这是预览模式，不会写入真实宾客名单。':attendance==='going'?`已为 ${name} 登记 ${pax} 位出席。资料已同步给新人。`:`${name}，谢谢你的回复与祝福。`;document.getElementById('inviteConfirm').classList.remove('hidden');f.reset()}catch(err){console.error(err);e.textContent='提交失败：'+(err.message||'请稍后重试');e.style.display='block'}finally{if(btn){btn.disabled=false;btn.textContent='提交 RSVP · Send Response'}}};
bootInvitationRoute=async function(){ensureInviteDefaults();cloudState();saveState(true);await init();const u=new URL(location.href),isGuest=u.searchParams.get('view')==='guest',t=u.searchParams.get('invite');if(isGuest){document.getElementById('landing')?.classList.add('hidden');document.getElementById('planner')?.classList.add('hidden');if(!t)return invalid();try{const q=await sb.rpc('get_public_invitation',{p_token:t});if(q.error)throw q.error;const r=Array.isArray(q.data)?q.data[0]:q.data;if(!r)return invalid();applyInvite(r,t);preview=false;openGuestInvitation(false)}catch(e){console.error(e);invalid('暂时无法读取电子请柬')}}else if(user&&state.cloud?.invitationId)watchGuests()};
renderSettings=function(){document.getElementById('view-settings').innerHTML=pageHead('Preferences & Cloud','设置与云端','本地自动保存继续保留；Supabase 负责跨设备 RSVP、宾客与桌席同步。')+`<div class="settings-grid"><div class="card setting-card"><h3>☁ Supabase 云端数据库</h3><p class="muted" style="font-size:12px;line-height:1.8">状态：<b>${signed()?esc(user.email||'已登录'):'已连接 · 未登录'}</b><br>Project：ztpxjwqjnrosdagsasjk.supabase.co</p><div style="font-size:10px;color:#8c827c">网页仅使用 Publishable key，不含 service_role / secret key。</div></div><div class="card setting-card"><h3>新人账号</h3><input class="field" id="cloudEmail" type="email" placeholder="Email"><input class="field" id="cloudPassword" type="password" placeholder="Password (6+)" style="margin-top:8px"><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px">${user?`<button class="btn btn-secondary btn-small" onclick="xhjLogout()">退出账号</button>`:`<button class="btn btn-primary btn-small" onclick="xhjAuth('login')">登录</button><button class="btn btn-secondary btn-small" onclick="xhjAuth('signup')">注册账号</button>`}</div><div style="font-size:10px;color:#8c827c;margin-top:8px">若 Supabase 开启 Email confirmation，注册后先确认邮箱。</div></div><div class="card setting-card"><h3>数据库同步</h3><p class="muted" style="font-size:12px;line-height:1.7">把电子请柬、宾客、桌席上传云端；宾客 RSVP 会进入同一份宾客管理资料。</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-primary btn-small" onclick="xhjUpload()">↑ 上传目前资料</button><button class="btn btn-secondary btn-small" onclick="xhjPull()">↓ 读取云端 RSVP</button></div></div><div class="card setting-card"><h3>婚礼资料</h3><p class="muted" style="font-size:12px;line-height:1.7">${esc(coupleName())}<br>${esc(weddingDateText())}<br>${esc(state.profile.venue||'场地未设置')}</p><button class="btn btn-secondary btn-small" onclick="openSetup()">编辑资料</button></div><div class="card setting-card"><h3>备份与迁移</h3><button class="btn btn-secondary btn-small" onclick="exportData()">导出 JSON</button></div></div>`};
Object.assign(window,{xhjAuth:auth,xhjLogout:logout,xhjUpload:uploadAll,xhjPull:pullAll,xhjPushInvite:()=>pushInvite(true)});
init().then(()=>{if(guestRoute())bootInvitationRoute();else if(user&&state.cloud?.invitationId)watchGuests();updateShell()});
})();